services:
  - type: web
    name: koms-backend
    runtime: docker
    repo: https://github.com/mtmohan012005-rgb/KOMS.git
    branch: main
    region: singapore
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: mysql-3f01fdf9-mtmohan012005-1250.h.aivencloud.com
      - key: DB_USER
        value: avnadmin
      - key: DB_NAME
        value: defaultdb
      - key: DB_PORT
        value: "15346"
      - key: PORT
        value: "10000"
