org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
org.gradle.java.home=C\:\\Users\\mohan\\.jdks\\jbr-17.0.14
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=C\:\\Users\\mohan\\.jdks\\jbr-17.0.14
