-- KOMS seed file intentionally disabled.
-- No default/demo users, passwords, students, masters, seniors,
-- or other test records are created automatically.
-- Create real accounts through the KOMS application only.
